project:
  type: website

website:
  title: "Erika Austhof"
  navbar:
    left:
      - href: home.qmd
      - research.qmd
      - teaching.qmd
      - consulting.qmd
      - publications.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

