project:
  type: website

website:
  title: "Erika Austhof"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - consulting.qmd
      - publications.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: $oc-orange-8
    css: styles.css
    toc: true

editor: visual

