project:
  type: website
  output-dir: docs

website: 
  title: "Erika Austhof"
  navbar:
    left:
      - href: index.qmd
      - research.qmd
      - teaching.qmd
      - consulting.qmd
      - publications.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

