---
title: "Research"
---

# Research Interests

My research focuses on the intersection of climate change and health. I focus on epidemiological study design and data science approaches in my research which has allowed me to explore a variety of climate change health outcomes and infectious diseases and their long term health outcomes.

# Current Work

-   Exploring transmission dynamics of *Salmonella* through shotgun metagenomics and whole genome sequencing (UAHS Careeer Development Award 2025-2027)

-   Exploring transmission of pathogens from cattle feedlots to adjacent lands (Center for Produce Safety 2025-2027 grant)

-   Gastrointestinal symptoms and health outcomes of COVID-19 (NIH NIDDK R01, co-I)

-   Cardiovascular health outcomes of wildfire smoke exposure (CLIMAS NOAA RISA grant)

-   Technical assistance to health departments responding to the health effects of climate change (BRACE, CDC)

## Thinking about...

-   How are migratory birds involved in transmission dynamics of foodborne pathogens?

-   Do regenerative agriculture practices support soil health, and reduce pathogen transmission?
